import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    paddingHorizontal: 15,
    gap: 18,
  },
  challengeInfoContainer: {
    paddingVertical: 15,
    paddingHorizontal: 10,
    marginBottom: 10,
    borderRadius: 20,
    borderWidth: 1,
    borderBottomWidth: 7,
    gap: 10,
  },
  badgeText: {
    borderRadius: 20,
    width: '40%',
    textAlign: 'center',
    padding: 8,
    fontFamily: 'Fredoka-Bold',
    fontSize: 13,
  },
  normalHeadingText: {
    fontFamily: 'Fredoka-Bold',
    fontSize: 16,
  },
  playAear: {
    backgroundColor: '#fff',
    paddingVertical: 12,
    paddingHorizontal: 12,
    alignItems: 'center',
    borderWidth: 1,
    borderBottomWidth: 7,
    borderRadius: 10,
    height: '62%',
    justifyContent: 'space-around',
  },
  speakBtn: {
    height: '10%',
    width: '13%',
    position: 'absolute',
    right: 10,
    top: 10,
  },
  questionText: {
    fontFamily: 'Fredoka-Bold',
    fontSize: 20,
    width: '85%',
    textAlign: 'left',
    alignSelf: 'flex-start',
    letterSpacing: 0.8,
  },
  targetLetterContainer: {
    width: '100%',
    height: '30%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 10,
    borderWidth: 1,
    borderRadius: 15,
    borderBottomWidth: 7,
  },
  characterFeeback: {
    height: '100%',
    width: '37%',
    alignSelf: 'center',
    marginTop: 0,
  },
  letterEmojiSection: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    width: '50%',
  },
  dropArea: {
    width: '62%',
    height: '70%',
  },
  emoji: {
    fontSize: 100,
    lineHeight: 120,
    right: 55,
  },
  optionsContainer: {
    width: '100%',
    height: '50%',
    padding: 10,
    borderRadius: 20,
  },
});
