import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    paddingHorizontal: 15,
    gap: 9,
  },
  traceSection: {
    flex: 1,
    minHeight: 250,
  },
  traceCard: {
    flex: 1,
    borderWidth: 1.5,
    borderBottomWidth: 7,
    borderRadius: 12,
    overflow: 'hidden',
  },
  startBadge: {
    position: 'absolute',
    top: 14,
    left: 14,
    backgroundColor: '#ffffffee',
    borderRadius: 40,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: '#ff8a2b',
  },
  startBadgeText: {
    fontFamily: 'Fredoka-Bold',
    color: '#d84e16',
    fontSize: 12,
  },
  infoSection: {
    minHeight: 110,
    borderWidth: 1,
    borderBottomWidth: 6,
    borderRadius: 10,
    padding: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  feedbackCopy: {
    flex: 1,
    gap: 6,
  },
  letterPill: {
    width: 54,
    height: 54,
    borderRadius: 10,
    backgroundColor: '#ffffffd9',
    justifyContent: 'center',
    alignItems: 'center',
  },
  letterPillText: {
    fontFamily: 'Fredoka-Bold',
    fontSize: 32,
  },
  statusText: {
    fontFamily: 'Fredoka-Bold',
    fontSize: 17,
    color: '#1a105f',
  },
  hintText: {
    fontFamily: 'Fredoka-Bold',
    fontSize: 12,
    color: '#7d7d7d',
    lineHeight: 16,
  },
  characterImage: {
    width: 92,
    height: 92,
    resizeMode: 'contain',
  },
  sliderSection: {
    backgroundColor: '#fff',
    borderRadius: 10,
  },
  sliderTitle: {
    paddingTop: 11,
    textAlign: 'center',
    fontFamily: 'Fredoka-Bold',
    fontSize: 13,
    color: '#9e9e9e',
  },
  sliderList: {
    gap: 10,
    paddingVertical: 12,
  },
  sliderItem: {
    width: 48,
    height: 48,
    borderRadius: 10,
    borderWidth: 2,
    justifyContent: 'center',
    alignItems: 'center',
  },
  sliderLetter: {
    fontFamily: 'Fredoka-Bold',
    fontSize: 24,
  },
  actionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  roundAction: {
    width: 56,
    height: 56,
    // borderRadius: 18,
    justifyContent: 'center',
    alignItems: 'center',
    // borderBottomWidth: 6,
    // borderBottomColor: '#d84d16ce',
  },
  buttonContent: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
  },
  buttonText: {
    fontFamily: 'Fredoka-Bold',
    color: '#fff',
    fontSize: 21,
  },
  buttonIcon: {
    backgroundColor: '#ffffff66',
    paddingHorizontal: 11,
    paddingVertical: 8,
    borderRadius: 20,
  },
});
